apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/pullrequest.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-make-linux
          resources: {}
        - name: build-make-test
          resources: {}
        - name: build-container-build
          resources: {}
  taskRunTemplate:
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 24h0m0s
    tasks: 24h0m0s
